#!/usr/bin/env python3
"""
Investigate why signals are not being executed.

This script analyzes the complete signal execution pipeline:
1. Signal generation status
2. Bot health / pause status
3. Risk manager checks
4. Config settings
5. OrderManager readiness
"""

import sys
import yaml
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

def check_config():
    """Check if system is in paper mode."""
    print("\n" + "="*80)
    print("STEP 1: CHECK TRADING MODE")
    print("="*80)

    config_path = PROJECT_ROOT / "config" / "config.yaml"
    with open(config_path) as f:
        config = yaml.safe_load(f)

    system_mode = config.get("system", {}).get("mode", "unknown")
    print(f"✓ System mode: {system_mode}")

    if system_mode == "paper":
        print("  ⚠️  PAPER MODE ENABLED - Trades will NOT execute on live MT5")
        print("     To enable live trading, set config.system.mode = 'live'")
    elif system_mode == "live":
        print("  ✅ LIVE MODE - Trades WILL execute on real account")

    # Check trading hours
    trading_start = config.get("trading", {}).get("session_start", "00:30")
    trading_end = config.get("trading", {}).get("session_end", "23:59")
    trading_days = config.get("trading", {}).get("days", [0,1,2,3,4])
    print(f"✓ Trading hours: {trading_start} to {trading_end}")
    print(f"✓ Trading days: {trading_days} (0=Mon, 4=Fri)")

    # Check signal execution interval
    signal_exec_interval = config.get("scheduler", {}).get("signal_outcome_check_interval", 900)
    print(f"✓ Signal execution check interval: {signal_exec_interval} seconds ({signal_exec_interval//60} min)")

    return config

def check_bot_health():
    """Check if bot is paused."""
    print("\n" + "="*80)
    print("STEP 2: CHECK BOT HEALTH / PAUSE STATUS")
    print("="*80)

    print("⚠️  Database connection required to check bot_health table")
    print("   Expected checks:")
    print("   - CIRCUIT_BREAKER (20% drawdown limit)")
    print("   - MANUAL_PAUSE (via /pause command)")
    print("   - NEWS_BLACKOUT (via /news_blackout command)")
    print("\n   🔧 If signals not executing, check:")
    print("      telegram: /status   <- Shows if bot is PAUSED")
    print("      telegram: /resume   <- Clears any pause")

def check_risk_manager():
    """Check what risk checks might block signals."""
    print("\n" + "="*80)
    print("STEP 3: RISK MANAGER CHECKS")
    print("="*80)

    config_path = PROJECT_ROOT / "config" / "config.yaml"
    with open(config_path) as f:
        config = yaml.safe_load(f)

    risk_cfg = config.get("risk_management", {})

    checks = [
        ("Bot Paused", "Check bot_health for MANUAL_PAUSE / CIRCUIT_BREAKER"),
        ("Blocked Pairs", f"blocked_pairs: {risk_cfg.get('blocked_pairs', [])}"),
        ("News Blackout", "Check bot_health for NEWS_BLACKOUT"),
        ("Strategy Active", "Check if strategy is enabled in strategies.yaml"),
        ("Market Regime", f"use_macro_regime_filter: {risk_cfg.get('use_macro_regime_filter', False)}"),
        ("Max Concurrent", f"max_concurrent_positions: {risk_cfg.get('max_concurrent_positions', 5)}"),
        ("Max Lot Size", f"max_lot_size: {risk_cfg.get('max_lot_size', 1.0)}"),
        ("Margin Check", "Requires sufficient free margin in MT5"),
        ("Max Spread", f"max_spread_pips: {risk_cfg.get('max_spread_pips', 5)}"),
        ("Trading Hours", "Must be within configured hours/days"),
        ("HTF Trend", "D1 EMA 200 alignment (if enabled)"),
        ("Macro Bias", "Global bias alignment (if enabled)"),
    ]

    print("Risk Manager runs these checks on every signal:\n")
    for i, (check_name, detail) in enumerate(checks, 1):
        print(f"{i:2}. {check_name:20} - {detail}")

    print("\n⚠️  ANY FAILED CHECK BLOCKS SIGNAL EXECUTION")

def check_signal_generation():
    """Check signal generation."""
    print("\n" + "="*80)
    print("STEP 4: SIGNAL GENERATION")
    print("="*80)

    print("Signals are generated by:")
    print("  1. Strategies running in forward_test/paper_engine.py")
    print("  2. run_detect() scans for signals (1-min frequency)")
    print("  3. run_execute() attempts to execute pending signals (5-min frequency)")
    print("\nSignal generation is AUTOMATIC when:")
    print("  ✓ daily_paper_trading_cycle.py is called")
    print("  ✓ main.py --mode paper-trade is running")
    print("  ✓ Scheduled task 'DailyAutomation-v2-Integrated' is active")
    print("\nTo verify signals ARE being generated:")
    print("  1. Check results/signals table in database")
    print("  2. Run: telegram /signals")
    print("  3. View results/overnight/YYYYMMDD_backtest_report.md")

def check_execution_flow():
    """Explain the complete execution flow."""
    print("\n" + "="*80)
    print("STEP 5: COMPLETE EXECUTION FLOW")
    print("="*80)

    flow = """
    DAILY AUTOMATION CYCLE:
    ┌─────────────────────────────────────────────────────────┐
    │ scripts/daily_automation_v2.py                          │
    │ ├─ STEP 1: Validate components                         │
    │ ├─ STEP 2: Check Docker status                         │
    │ ├─ STEP 3: Run overnight backtest (if Docker UP)       │
    │ ├─ STEP 4: Post to Telegram                            │
    │ └─ STEP 5: Cleanup & Backup                            │
    └─────────────────────────────────────────────────────────┘

    SIGNAL EXECUTION CYCLE (every 5 minutes):
    ┌─────────────────────────────────────────────────────────┐
    │ forward_test/paper_engine.py :: PaperEngine             │
    │ ├─ run_detect()                                         │
    │ │  ├─ Fetch signals from database                       │
    │ │  ├─ Check signal validity                            │
    │ │  └─ Store signal in signals table                    │
    │ │                                                      │
    │ └─ run_execute()                                        │
    │    ├─ For each signal:                                 │
    │    │  ├─ risk_manager.check_all()    ← Can BLOCK here  │
    │    │  ├─ Calculate SL/TP targets                       │
    │    │  ├─ Calculate lot size                            │
    │    │  └─ order_manager.open_position()  ← EXECUTES     │
    │    │                                                  │
    │    └─ Log trade to database                            │
    └─────────────────────────────────────────────────────────┘

    MOST LIKELY BLOCKAGE POINTS:
    1. Bot paused (MANUAL_PAUSE in bot_health)
    2. Risk check failure (details in logs)
    3. Trading hours restriction
    4. Paper mode blocking execution
    5. No free margin in MT5
    6. Signal validity expired
    """
    print(flow)

def check_paper_engine():
    """Check PaperEngine code for execution paths."""
    print("\n" + "="*80)
    print("STEP 6: PAPER ENGINE EXECUTION PATHS")
    print("="*80)

    paper_engine_path = PROJECT_ROOT / "forward_test" / "paper_engine.py"

    if paper_engine_path.exists():
        with open(paper_engine_path) as f:
            content = f.read()

        # Check for key methods
        methods = [
            ("run_detect", "Signal detection (1-min scan)"),
            ("run_execute", "Trade execution (5-min scan)"),
            ("_process_symbol", "Process single symbol for signals"),
            ("order_manager.open_position", "Submit order to MT5"),
        ]

        print("Key execution methods found:\n")
        for method, description in methods:
            found = "✓" if method in content else "✗"
            print(f"  {found} {method:35} - {description}")

        # Check mode handling
        if "if mode == 'detect'" in content:
            print("\n✓ Mode-based execution logic found")
            print("  - detect mode: Scans for signals only")
            print("  - execute mode: Processes and executes signals")

        # Check risk manager check
        if "risk_manager.check_all" in content:
            print("\n✓ Risk manager integration found")
            print("  - Checks run before order submission")

        if "order_manager.open_position" in content:
            print("\n✓ OrderManager integration found")
            print("  - Positions submitted via order_manager.open_position()")

def main():
    print("\n" + "█"*80)
    print("█" + " "*78 + "█")
    print("█  TRADEPANEL SIGNAL EXECUTION INVESTIGATION".ljust(78) + "█")
    print("█" + " "*78 + "█")
    print("█"*80)

    try:
        config = check_config()
        check_bot_health()
        check_risk_manager()
        check_signal_generation()
        check_execution_flow()
        check_paper_engine()

        print("\n" + "="*80)
        print("SUMMARY & NEXT STEPS")
        print("="*80)

        print("\n🔍 WHY SIGNALS MIGHT NOT BE EXECUTING:")
        print("\n1. BOT IS PAUSED")
        print("   └─ Check: telegram /status")
        print("   └─ Fix: telegram /resume")

        print("\n2. SYSTEM IN PAPER MODE")
        print("   └─ Config: config/config.yaml → system.mode = 'paper'")
        print("   └─ Fix: Change to 'live' to execute real trades")

        print("\n3. RISK CHECK BLOCKING SIGNAL")
        print("   └─ Check: scripts/risk/manager.py :: check_all()")
        print("   └─ May fail on: margin, spread, trading hours, etc.")

        print("\n4. DAILY AUTOMATION NOT RUNNING")
        print("   └─ Check: Windows Task Scheduler 'DailyAutomation-v2-Integrated'")
        print("   └─ Or run manually: python scripts/daily_automation_v2.py")

        print("\n5. NO FREE MARGIN IN MT5 ACCOUNT")
        print("   └─ Check: telegram /balance")
        print("   └─ Need: Free margin > SL_distance * lot_size * tick_value")

        print("\n" + "="*80)
        print("RECOMMENDED ACTIONS")
        print("="*80)

        print("\n✅ ENABLE LIVE TRADING:")
        print("   1. Edit config/config.yaml")
        print("   2. Change: system.mode = 'live'")
        print("   3. Restart daily automation")

        print("\n✅ RESUME BOT IF PAUSED:")
        print("   1. In Telegram: /status")
        print("   2. If paused, run: /resume")

        print("\n✅ TEST SIGNAL APPROVAL FLOW:")
        print("   1. Wait for next signal generation")
        print("   2. Check telegram /signals")
        print("   3. Monitor results/cleanup_backup.log")

        print("\n✅ ADD TELEGRAM APPROVAL COMMAND:")
        print("   We can implement /approve_trade <signal_id>")
        print("   This would require:")
        print("     - Add command to notifications/router.py")
        print("     - Add approval_pending flag to signals table")
        print("     - Modify paper_engine.py to respect approval flag")

        print("\n" + "█"*80 + "\n")

    except Exception as e:
        print(f"\n❌ Investigation error: {e}")
        import traceback
        traceback.print_exc()
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main())
